package com.xiaowei.market.bean.db;

import java.util.Date;

import com.xiaowei.market.bean.entiy.IdEntity;
import lombok.Getter;
import lombok.Setter;
/**
 * 
 * WARNING:
 * this code is generated by code-generator
 * please DO NOT modify this file
 * @author code-generator
 * @date 2020-04-16 16:26:12
 */
@Getter
@Setter
public class MiaoshaUser extends IdEntity {
  private String nickname;
  /**
   * MD5(MD5(pass明文+固定salt) + salt)
   */
  private String password;
  private String salt;
  /**
   * 头像，云存储的ID
   */
  private String head;
  /**
   * 注册时间
   */
  private Date registerDate;
  /**
   * 上蔟登录时间
   */
  private Date lastLoginDate;
  /**
   * 登录次数
   */
  private Integer loginCount;

}
