package com.xiaowei.market.bean.db;

import java.math.BigDecimal;
import java.util.Date;

import com.xiaowei.market.bean.entiy.IdEntity;
import lombok.Getter;
import lombok.Setter;
/**
 * 
 * WARNING:
 * this code is generated by code-generator
 * please DO NOT modify this file
 * @author code-generator
 * @date 2020-04-16 16:24:56
 */
@Getter
@Setter
public class MiaoshaMessage extends IdEntity {
  /**
   * 分布式id
   */
  private Long messageid;
  /**
   * 消息内容
   */
  private String content;
  /**
   * 创建时间
   */
  private Date createTime;
  /**
   * 1 有效 2 失效 
   */
  private Integer status;
  /**
   * 结束时间
   */
  private Date overTime;
  /**
   * 0 秒杀消息 1 购买消息 2 推送消息
   */
  private Integer messageType;
  /**
   * 发送类型 0 app 1 pc 2 ios
   */
  private Integer sendType;
  /**
   * 商品名称
   */
  private String goodName;
  /**
   * 商品价格
   */
  private BigDecimal price;

}
