package com.xiaowei.market.bean.db;

import java.math.BigDecimal;
import java.util.Date;

import com.xiaowei.market.bean.entiy.IdEntity;
import lombok.Getter;
import lombok.Setter;
/**
 * 
 * WARNING:
 * this code is generated by code-generator
 * please DO NOT modify this file
 * @author code-generator
 * @date 2020-04-16 16:27:36
 */
@Getter
@Setter
public class OrderInfo extends IdEntity {
  /**
   * 用户ID
   */
  private Long userId;
  /**
   * 商品ID
   */
  private Long goodsId;
  /**
   * 收获地址ID
   */
  private Long deliveryAddrId;
  /**
   * 冗余过来的商品名称
   */
  private String goodsName;
  /**
   * 商品数量
   */
  private Integer goodsCount;
  /**
   * 商品单价
   */
  private Double goodsPrice;
  /**
   * 1pc，2android，3ios
   */
  private Integer orderChannel;
  /**
   * 订单状态，0新建未支付，1已支付，2已发货，3已收货，4已退款，5已完成
   */
  private Integer status;
  /**
   * 订单的创建时间
   */
  private Date createDate;
  /**
   * 支付时间
   */
  private Date payDate;

}
